In [14]:
import torch
import utils.globals as uglobals

In [18]:
data = torch.load("../data/musdb18/debug/sample_1b/level_2/data.pth.tar")
print(data)
for z in data['zs']:
    print(z.shape)
    print(z.dtype)

{'zs': [tensor([], device='cuda:0', size=(16, 0), dtype=torch.int64), tensor([], device='cuda:0', size=(16, 0), dtype=torch.int64), tensor([[1597,  255, 1224,  ..., 2039,   81, 1936],
        [1489,  653,  653,  ...,  381, 1374, 1503],
        [1853, 1941, 1431,  ..., 1301, 1038,  515],
        ...,
        [1489,  653,  653,  ..., 1865,  251,  588],
        [1434, 1489,  653,  ..., 2043, 1445, 1597],
        [1489,  653,  653,  ...,  784, 1489, 1869]], device='cuda:0')], 'labels': [{'y': tensor([[7938000,       0,   65536,     145,      11,      -1,      -1,      -1,
              -1],
        [7938000,       0,   65536,     454,       2,       8,      -1,      -1,
              -1],
        [7938000,       0,   65536,     121,      51,      14,      -1,      -1,
              -1],
        [7938000,       0,   65536,    1042,       9,      -1,      -1,      -1,
              -1],
        [7938000,       0,   65536,     557,      14,      -1,      -1,      -1,
              -1],
      

In [15]:
path = '../results/outputs/musdb18/z_out/finetune_vocal2acc_checkpoint_step_15001.pth.tar/demo.pt'
data_out = torch.load(path)
torch.save(data_out, path[:-3] + 'backup.pt')
out = {'zs': [torch.empty((1, 0)).long(), torch.empty((1, 0)).long(), data_out['z_pred']]}
torch.save(out, path)
for o in out['zs']:
    print(o.shape)


torch.Size([1, 0])
torch.Size([1, 0])
torch.Size([1, 3071])


In [9]:
data = torch.load("../results/outputs/musdb18/oracle/train/acc/z/A Classic Education - NightOwl_0_0.pt")
for d in data:
    print(d.shape)
    print(d[:, :10])

torch.Size([1, 330750])
tensor([[ 774,  273,  498, 1522,  316, 1594,  331, 1064, 1559, 1760]],
       device='cuda:0')
torch.Size([1, 82687])
tensor([[ 295, 1667,  340,  225, 1883, 1619, 1474, 1139,  436, 1028]],
       device='cuda:0')
torch.Size([1, 20671])
tensor([[ 129,  341, 1798, 1103,  978, 1470, 2036, 1499,  921,  952]],
       device='cuda:0')


In [10]:
data = torch.load("../results/outputs/musdb18/oracle/train/acc/z/A Classic Education - NightOwl_0_1.pt")
for d in data:
    print(d.shape)
    print(d[:, :10])

torch.Size([1, 82687])
tensor([[ 295, 1667,  340,  225, 1883, 1619, 1474, 1139,  436, 1028]],
       device='cuda:0')
torch.Size([1, 20671])
tensor([[ 129,  341, 1798, 1103,  978, 1470, 2036, 1499,  921,  952]],
       device='cuda:0')


In [23]:
path = '../results/outputs/musdb18/z_out/finetune_lr_checkpoint_step_16001.pth.tar/Lyndsey Ollard - Catching Up_19753_78285.pt'
data = torch.load(path)
pred = {'zs': [torch.empty((1, 0)).long(), torch.empty((1, 0)).long(), data['z_pred']]}
oracle = {'zs': [torch.empty((1, 0)).long(), torch.empty((1, 0)).long(), data['z_true']]}
torch.save(pred, path[:-3]+'_pred.pt')
torch.save(oracle, path[:-3]+'_oracle.pt')
for z in pred['zs']:
    print(z.shape)
    print(z.dtype)

torch.Size([1, 0])
torch.int64
torch.Size([1, 0])
torch.int64
torch.Size([1, 3071])
torch.int64


In [2]:
round(3.5)

4

: 

In [1]:
import numpy as np
a = np.array([1])
float(a)

1.0