In [1]:
import torch
import utils.globals as uglobals

In [2]:
data = torch.load("./models/jukebox/sample_1b/level_2/data.pth.tar")
print(data)
for z in data['zs']:
    print(z.shape)
    print(z.dtype)

FileNotFoundError: [Errno 2] No such file or directory: './models/jukebox/sample_1b/level_2/data.pth.tar'

In [4]:
data_out = torch.load("../results/outputs/musdb18/oracle/train/acc/z/A Classic Education - NightOwl_0_2.pt")
# out = {'zs': [torch.empty((1, 0)).long(), torch.empty((1, 0)).long(), data_out[0]]}
# out = {'zs': [data_out[0]]}
# torch.save(out, uglobals.DEBUG_ACC_Z_PATH)
# print(out)
# for z in out['zs']:
#     print(z.shape)
#     print(z.dtype)
data_out


[tensor([[ 129,  341, 1798,  ..., 1965, 1592,  681]], device='cuda:0')]

In [9]:
data = torch.load("../results/outputs/musdb18/oracle/train/acc/z/A Classic Education - NightOwl_0_0.pt")
for d in data:
    print(d.shape)
    print(d[:, :10])

torch.Size([1, 330750])
tensor([[ 774,  273,  498, 1522,  316, 1594,  331, 1064, 1559, 1760]],
       device='cuda:0')
torch.Size([1, 82687])
tensor([[ 295, 1667,  340,  225, 1883, 1619, 1474, 1139,  436, 1028]],
       device='cuda:0')
torch.Size([1, 20671])
tensor([[ 129,  341, 1798, 1103,  978, 1470, 2036, 1499,  921,  952]],
       device='cuda:0')


In [10]:
data = torch.load("../results/outputs/musdb18/oracle/train/acc/z/A Classic Education - NightOwl_0_1.pt")
for d in data:
    print(d.shape)
    print(d[:, :10])

torch.Size([1, 82687])
tensor([[ 295, 1667,  340,  225, 1883, 1619, 1474, 1139,  436, 1028]],
       device='cuda:0')
torch.Size([1, 20671])
tensor([[ 129,  341, 1798, 1103,  978, 1470, 2036, 1499,  921,  952]],
       device='cuda:0')


In [1]:
20671 * 128 / 44100

59.997460317460316

In [7]:
a = torch.zeros(2, 3)
b = torch.tensor([[0, 0, 1], [1, 0, 0]])
print(a)
a[b == 1] = 666
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[  0.,   0., 666.],
        [666.,   0.,   0.]])